### ISSUE TITLE
群内发送消息无法转发至服务器

### ISSUE THREAD

**Issue by JiangQiYan713** [DreamVoid/Chat2QQ#29]
<strong>问题描述</strong>

群内发送消息无法转发至服务器，
并且后台会输出报错，删除原有配置文件
并重启服务器依旧无效

<strong>复现方法</strong>

以下为配置文件
```
# 游戏内配置
# 此部分配置只会影响 Minecraft 服务器内的聊天
general:
  # 是否允许bStats统计
  allow-bStats: true

  # 是否必须使用命令才能向QQ群发送聊天消息
  require-command-to-chat: false

  # 使用命令时是否同时向服务器内发送聊天消息
  command-also-broadcast-to-chat: true

  # 可用的世界，玩家只有在下面列出的世界中聊天才会被发送到QQ群
  available-worlds:
    - world
    - world_nether
    - world_the_end
    - survival_world
    - survival_world2
    - main

  # 是否将上面的列表用作黑名单，即玩家在上面列出的世界聊天不会发送到QQ群
  available-worlds-use-as-blacklist: false

  # QQ群消息广播到游戏内聊天的格式（可以使用样式代码）
  # 变量：
  # %groupname% - 群名称
  # %groupid% - 群号
  # %nick% - 发送者群名片
  # %qq% - 发送者QQ号
  # %message% - 消息内容
  in-game-chat-format: "&7%nick%(%qq%)：%message%"

  # 是否允许控制台使用聊天命令
  allow-console-chat: false

  # 如果作为控制台发送到QQ群的聊天消息，控制台要叫什么名字
  console-name: "控制台"

  # 游戏聊天前缀（聊天需要带有指定前缀才能发送到QQ群）
  requite-special-word-prefix:
    #启用这个功能
    enabled: false

    # 聊天前缀（可设置多个，群聊天只有带下面的前缀之一才会发送到服务器）
    prefix:
      - "#"

  # 当群名片不存在时是否尝试获取昵称
  use-nick-if-namecard-null: false

  # 启用 MiraiMC 内置的QQ绑定
  use-miraimc-bind: true

  # 已绑定玩家向服务器发送聊天消息的格式
  # 如果玩家没有绑定，消息格式仍按照上方设置的格式发送
  # 内置变量仍然可以使用
  bind-chat-format: "&7%nick%(%qq%)：%message%"

# 机器人配置
# 此部分配置只会影响到QQ群的聊天
bot:
  # 指定使用的QQ号，只有这个QQ号接收到的群消息才会被处理
  # 请至少设置一个
  bot-accounts:
    - 488345943

  # 指定接收指定群的群消息，只有这个群接收到的消息才会被处理
  # 请至少设置一个
  group-ids:
    - 383829380
    - 1165882956

  # 群聊天前缀（聊天需要带有指定前缀才能发送到服务器）
  requite-special-word-prefix:
    #启用这个功能
    enabled: false

    # 聊天前缀（可设置多个，群聊天只有带下面的前缀之一才会发送到服务器）
    prefix:
      - "#"

  # 服务器消息发送到QQ群的格式（可以使用PlaceholderAPI变量）
  # 自带变量：
  # %player% - 玩家显示昵称
  # %message% - 消息内容
  group-chat-format: "[%multiverse_world_alias%]<%player%> %message%"

  # 是否发送玩家进服退服消息
  send-player-join-quit-message: false

  # 进服消息
  # 自带变量：
  # %player% - 玩家显示昵称
  player-join-message: "%player% 进入服务器"

  # 退服消息
  # 自带变量：
  # %player% - 玩家显示昵称
  player-quit-message: "%player% 离开服务器"

```

<strong>版本类型</strong>

* Minecraft 服务端版本：Paper-1.18.1
* MiraiMC 插件版本：1.6
* Chat2QQ 插件版本：1.5

<strong>服务器日志</strong>

```
26.02 20:22:43 [服务器] FATAL Thread DefaultDispatcher-worker-2 failed main thread check: ChunkHolder update
26.02 20:22:43 [服务器] 信息 java.lang.Throwable: null
26.02 20:22:43 [服务器] 信息 at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.18.1.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at net.minecraft.server.level.ChunkHolder.addToBroadcastMap(ChunkHolder.java:314) ~[?:?]
26.02 20:22:43 [服务器] 信息 at net.minecraft.server.level.ChunkHolder.blockChanged(ChunkHolder.java:278) ~[?:?]
26.02 20:22:43 [服务器] 信息 at net.minecraft.server.level.ServerChunkCache.blockChanged(ServerChunkCache.java:1130) ~[?:?]
26.02 20:22:43 [服务器] 信息 at net.minecraft.server.level.ServerLevel.sendBlockUpdated(ServerLevel.java:1547) ~[?:?]
26.02 20:22:43 [服务器] 信息 at net.minecraft.world.level.block.entity.CommandBlockEntity$1.onUpdated(CommandBlockEntity.java:45) ~[?:?]
26.02 20:22:43 [服务器] 信息 at net.minecraft.world.level.BaseCommandBlock.sendMessage(BaseCommandBlock.java:180) ~[?:?]
26.02 20:22:43 [服务器] 信息 at org.bukkit.craftbukkit.v1_18_R1.命令.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33) ~[paper-1.18.1.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at org.bukkit.命令.CommandSender.sendMessage(CommandSender.java:128) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
26.02 20:22:43 [服务器] 信息 at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:253) ~[adventure-api-4.9.3.jar:?]
26.02 20:22:43 [服务器] 信息 at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:227) ~[adventure-api-4.9.3.jar:?]
26.02 20:22:43 [服务器] 信息 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1767) ~[paper-1.18.1.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1739) ~[paper-1.18.1.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcastMessage(CraftServer.java:644) ~[paper-1.18.1.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:420) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
26.02 20:22:43 [服务器] 信息 at me.dreamvoid.chat2qq.bukkit.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:58) ~[Chat2QQ-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source) ~[?:?]
26.02 20:22:43 [服务器] 信息 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
26.02 20:22:43 [服务器] 信息 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
26.02 20:22:43 [服务器] 信息 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
26.02 20:22:43 [服务器] 信息 at me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:97) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] ERROR Could not pass event MiraiGroupMessageEvent to Chat2QQ v1.5
26.02 20:22:43 [服务器] 信息 java.lang.IllegalStateException: Asynchronous ChunkHolder update!
26.02 20:22:43 [服务器] 信息 at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.18.1.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at net.minecraft.server.level.ChunkHolder.addToBroadcastMap(ChunkHolder.java:314) ~[?:?]
26.02 20:22:43 [服务器] 信息 at net.minecraft.server.level.ChunkHolder.blockChanged(ChunkHolder.java:278) ~[?:?]
26.02 20:22:43 [服务器] 信息 at net.minecraft.server.level.ServerChunkCache.blockChanged(ServerChunkCache.java:1130) ~[?:?]
26.02 20:22:43 [服务器] 信息 at net.minecraft.server.level.ServerLevel.sendBlockUpdated(ServerLevel.java:1547) ~[?:?]
26.02 20:22:43 [服务器] 信息 at net.minecraft.world.level.block.entity.CommandBlockEntity$1.onUpdated(CommandBlockEntity.java:45) ~[?:?]
26.02 20:22:43 [服务器] 信息 at net.minecraft.world.level.BaseCommandBlock.sendMessage(BaseCommandBlock.java:180) ~[?:?]
26.02 20:22:43 [服务器] 信息 at org.bukkit.craftbukkit.v1_18_R1.命令.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33) ~[paper-1.18.1.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at org.bukkit.命令.CommandSender.sendMessage(CommandSender.java:128) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
26.02 20:22:43 [服务器] 信息 at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:253) ~[adventure-api-4.9.3.jar:?]
26.02 20:22:43 [服务器] 信息 at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:227) ~[adventure-api-4.9.3.jar:?]
26.02 20:22:43 [服务器] 信息 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1767) ~[paper-1.18.1.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcast(CraftServer.java:1739) ~[paper-1.18.1.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at org.bukkit.craftbukkit.v1_18_R1.CraftServer.broadcastMessage(CraftServer.java:644) ~[paper-1.18.1.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:420) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
26.02 20:22:43 [服务器] 信息 at me.dreamvoid.chat2qq.bukkit.listener.onGroupMessage.onGroupMessageReceive(onGroupMessage.java:58) ~[Chat2QQ-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source) ~[?:?]
26.02 20:22:43 [服务器] 信息 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
26.02 20:22:43 [服务器] 信息 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-214]
26.02 20:22:43 [服务器] 信息 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
26.02 20:22:43 [服务器] 信息 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
26.02 20:22:43 [服务器] 信息 at me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:97) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[MiraiMC-Bukkit.jar:?]
26.02 20:22:43 [服务器] 信息 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[MiraiMC-Bukkit.jar:?]
```
