### ISSUE TITLE
无法发送消息至群

### ISSUE THREAD

**Issue by yuyuko233** [DreamVoid/Chat2QQ#6]
<strong>无法发送消息至群</strong>

无法发送消息至群
且无报错
![图片](https://user-images.githubusercontent.com/20128226/127857383-df9cc1ce-876d-41be-9fd8-591bc67f56de.png)
![图片](https://user-images.githubusercontent.com/20128226/127857271-344158df-e1e2-4632-b46b-2c0d9344ac56.png)
![图片](https://user-images.githubusercontent.com/20128226/127857307-b8c7848a-3f38-4cb6-87ae-d263ad4449ab.png)

<strong>复现方法</strong>

1. 发送消息

<strong>版本类型</strong>

* Minecraft 服务端版本：1.16.5
* MiraiMC 插件版本：1.3.1
* Chat2QQ 插件版本：1.2.2

<strong>服务器日志</strong>
无任何日志

```

```

**Comment by DreamVoid** [comment]
请确认配置文件中关闭```require-command-to-chat```和```requite-special-word-prefix```

**Comment by yuyuko233** [comment]
> 
> 
> 请确认配置文件中关闭`require-command-to-chat`和`requite-special-word-prefix`

已关闭

**Comment by yuyuko233** [comment]
> 
> 
> 请提供完整服务器日志和配置文件内容
> 提供时请使用两个“```”包围，或者点击编辑框上方的“<>”按钮，确保日志和配置文件显示起来像下面这样（可使用上方Preview）：
> 
> ```
> [00:00:00] [INFO] 这是日志应该有的样子
> ```
并没有任何的日志
![图片](https://user-images.githubusercontent.com/20128226/127859612-47b4246a-6bba-4e51-8dd0-3aebb96d5cf4.png)
![图片](https://user-images.githubusercontent.com/20128226/127859740-36949ced-4e13-4a16-98dd-61ba5d8e59c0.png)

**Comment by DreamVoid** [comment]
> > 请提供完整服务器日志和配置文件内容
> > 提供时请使用两个“```”包围，或者点击编辑框上方的“<>”按钮，确保日志和配置文件显示起来像下面这样（可使用上方Preview）：
> > ```
> > [00:00:00] [INFO] 这是日志应该有的样子
> > ```
> 
> 并没有任何的日志
> ![图片](https://user-images.githubusercontent.com/20128226/127859612-47b4246a-6bba-4e51-8dd0-3aebb96d5cf4.png)
> ![图片](https://user-images.githubusercontent.com/20128226/127859740-36949ced-4e13-4a16-98dd-61ba5d8e59c0.png)

请提供完整的配置文件

**Comment by yuyuko233** [comment]
> 请提供完整的配置文件
> 另外，请在服务器内分别输入指令`/chat2qq`和`/miraimc`，这两个命令将会提供插件的版本号，请同时提供这两个指令的执行结果
![图片](https://user-images.githubusercontent.com/20128226/127860559-3cd8ec56-d745-4835-8185-b4a57ae68eb5.png)

```yaml
# 游戏内配置
# 此部分配置只会影响 Minecraft 服务器内的聊天
general:
  # 是否允许bStats统计
  allow-bStats: true

  # 是否必须使用命令才能向QQ群发送聊天消息
  require-command-to-chat: false

  # 使用命令时是否同时向服务器内发送聊天消息
  command-also-broadcast-to-chat: true

  # 可用的世界，玩家只有在下面列出的世界中聊天才会被发送到QQ群
  available-worlds:
    - spawn

  # 是否将上面的列表用作黑名单，即玩家在上面列出的世界聊天不会发送到QQ群
  available-worlds-use-as-blacklist: true

  # QQ群消息广播到游戏内聊天的格式（可以使用样式代码）
  # 变量：
  # %groupname% - 群名称
  # %groupid% - 群号
  # %nick% - 发送者群名片
  # %qq% - 发送者QQ号
  # %message% - 消息内容
  in-game-chat-format: "&6[&a%nick%(%qq%)&6]&r: %message%"

  # 是否允许控制台使用聊天命令
  allow-console-chat: false

  # 如果作为控制台发送到QQ群的聊天消息，控制台要叫什么名字
  console-name: "控制台"

  # 游戏聊天前缀（聊天需要带有指定前缀才能发送到QQ群）
  requite-special-word-prefix:
    #启用这个功能
    enabled: false

    # 聊天前缀（可设置多个，群聊天只有带下面的前缀之一才会发送到服务器）
    prefix:
      - "#"

  # 是否替换聊天消息中的图片内容
  # 图片将会替换成“[图片]”
  replace-image-string: true

  # 当群名片不存在时是否尝试获取昵称
  # 仅在 MiraiMC 1.3-rc2 及之后的版本中生效
  use-nick-if-namecard-null: true

  # 启用 MiraiMC 内置的QQ绑定
  # 仅在 MiraiMC 1.3.1 及之后的版本中生效
  use-miraimc-bind: true

  # 已绑定玩家向服务器发送聊天消息的格式
  # 如果玩家没有绑定，消息格式仍按照上方设置的格式发送
  # 内置变量仍然可以使用
  bind-chat-format: "&6[QQ]&r %vault_prefix%%player_name%%vault_suffix%: %message%"

# 机器人配置
# 此部分配置只会影响到QQ群的聊天
bot:
  # 指定使用的QQ号，只有这个QQ号接收到的群消息才会被处理
  botaccount: 31xxxxxx72

  # 指定接收指定群的群消息，只有这个群接收到的消息才会被处理
  groupid: 78xxxxx82

  # 群聊天前缀（聊天需要带有指定前缀才能发送到服务器）
  requite-special-word-prefix:
    #启用这个功能
    enabled: false

    # 聊天前缀（可设置多个，群聊天只有带下面的前缀之一才会发送到服务器）
    prefix:
      - "#"

  # 服务器消息发送到QQ群的格式（可以使用PlaceholderAPI变量）
  # 自带变量：
  # %player% - 玩家显示昵称
  # %message% - 消息内容
  group-chat-format: "[MC] %player%: %message%"
```
